Lesson 2
OlegZhdanoff/django_basic pull request #2
Opened 2020-12-04 08:54 UTC by OlegZhdanoff

2020-12-08 07:14 UTC, OlegZhdanoff commented
комментарий для примера

2020-12-08 07:27 UTC, Vokler requested changes

2020-12-08 07:27 UTC, Vokler commented on geekshop/mainapp/views.py
> +from .services import *
Рекомендую использовать (вернее не я, а pep8) абсолютный импорт, то есть from mainapp.services
https://www.python.org/dev/peps/pep-0008/#id23

Но с импортом еще более-менее лояльно, то есть допускается и ваше вариант, но импортировать все, используя * - не хорошая практика. Потому что таким образом импортируется абсолютно все, что в файле services.py, даже импорты из этого файла. В некоторых случаях это может привезти к ошибке при запуске сервера.

2020-12-08 07:27 UTC, Vokler commented on geekshop/mainapp/services.py
> +    with open(os.path.join(settings.CONTENTFILES_DIR, file), 'rt', encoding='utf-8') as content_file:
Хорошая идея, в целом мне понравилось, что вы так решили хранить контент.
Возможно только (как совет), я бы на вашем месте перенес папку content в mainapp, так как content относится только к mainapp. Если с учетом на будущее для других приложений - то в каждом приложении можно было бы создавать папку content.

Вообще в крупных проектах что-то подобно есть и оно называется fixtures.
https://code.djangoproject.com/wiki/Fixtures

2020-12-09 04:24 UTC, OlegZhdanoff commented on geekshop/mainapp/services.py
> +    with open(os.path.join(settings.CONTENTFILES_DIR, file), 'rt', encoding='utf-8') as content_file:
перенес в приложение.

2020-12-09 06:56 UTC, OlegZhdanoff commented on geekshop/mainapp/views.py
> +from .services import *
исправил, видимо на автомате так написал

2020-12-09 10:57 UTC, Vokler approved these changes

2020-12-09 10:57 UTC, merged